# src/main/resources/application-prod.yml
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:snowflake://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com?warehouse=${SNOWFLAKE_WAREHOUSE}&db=${SNOWFLAKE_DATABASE}&schema=${SNOWFLAKE_SCHEMA}&JDBC_QUERY_RESULT_FORMAT=JSON}
    username: ${SPRING_DATASOURCE_USERNAME:${SNOWFLAKE_USER:}}
    password: ${SPRING_DATASOURCE_PASSWORD:${SNOWFLAKE_PWD:${SNOWFLAKE_TOKEN:}}}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 0
      idle-timeout: 300000
      connection-timeout: 30000
      initialization-fail-timeout: -1
      data-source-properties:
        ENABLE_ARROW_RESULTSET: false

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  sql:
    init:
      continue-on-error: true

logging:
  level:
    root: INFO
